### ISSUE TITLE
PHP-7.4-ts-ubuntu-gcc-x64 stopped to setup

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#657]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
7.4

**To Reproduce**
https://github.com/niden/cphalcon/actions/runs/3356225528/jobs/5561136530#step:4:25

**Expected behavior**
Setup PHP as another versions in same matrix.

**Comment by shivammathur** [comment]
Added zts build for PHP 7.4 in https://github.com/shivammathur/php-builder/commit/f8e5aa7af5c2e1d431f9ee4701a6d00c2fa91fb4
Please re-run your workflow, it should work now.
Test workflows: https://github.com/shivammathur/test-setup-php/actions/runs/3375496331/workflow

**Comment by niden** [comment]
@shivammathur It still does not work for us. From what I can tell, your test uses 7.4.32 where in our environments 7.4.33 is installed. For that particular one, `yaml` fails to install.

https://github.com/niden/cphalcon/actions/runs/3377925243/jobs/5607490223

Anything we can do on our end?

**Comment by shivammathur** [comment]
I will add yaml extension in the zts builds

**Comment by shivammathur** [comment]
Added `yaml`.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/3375496331/workflow

**Comment by niden** [comment]
Thank you @shivammathur
