### ISSUE TITLE
PHP8.3 + gd: Unable to load dynamic library 'gd.so'

### ISSUE THREAD

**Issue by tinect** [shivammathur/setup-php#767]
**Describe the bug**
PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20230831/gd.so (/usr/lib/php/20230831/gd.so: undefined symbol: gdImageCreateFromAvif), /usr/lib/php/20230831/gd.so.so (/usr/lib/php/20230831/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.3

**To Reproduce**
```
- uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
```

**Expected behavior**
No warning and working setup.

**Additional context**
https://github.com/tinect/flysystem-garbage/actions/runs/6208371225/job/16855844375#step:3:13

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@tinect 

Thanks for reporting this.

Fixed in https://github.com/shivammathur/php-builder/commit/7e17fdd791a26c53b038c2536fab21b937a7faca

Please restart your workflow, it should work now.

**Comment by jasonvarga** [comment]
If I'm still seeing the warning, have I done something wrong?

Here's the log if it helps.

```
2023-10-30T15:03:44.9458291Z [command]/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
2023-10-30T15:03:44.9594276Z 
2023-10-30T15:03:44.9595014Z [90;1m==> [0m[37;1mSetup PHP[0m
2023-10-30T15:03:56.7729978Z [32;1m✓ [0m[34;1mPHP [0m[90;1mInstalled PHP 8.3.0-dev (81e236cde56ff006d9c661140790b42f40ffc43b)[0m
2023-10-30T15:03:56.7730858Z 
2023-10-30T15:03:56.7731118Z [90;1m==> [0m[37;1mSetup Extensions[0m
2023-10-30T15:03:56.7901978Z PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20230831/gd.so (/usr/lib/php/20230831/gd.so: undefined symbol: gdImageCreateFromAvif), /usr/lib/php/20230831/gd.so.so (/usr/lib/php/20230831/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
2023-10-30T15:03:56.8308536Z [32;1m✓ [0m[34;1mdom [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8356136Z [32;1m✓ [0m[34;1mcurl [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8390827Z [32;1m✓ [0m[34;1mlibxml [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8429420Z [32;1m✓ [0m[34;1mmbstring [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8462828Z [32;1m✓ [0m[34;1mzip [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8500364Z [32;1m✓ [0m[34;1mpcntl [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8535969Z [32;1m✓ [0m[34;1mpdo [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8576207Z [32;1m✓ [0m[34;1msqlite3 [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8594948Z [32;1m✓ [0m[34;1mpdo_sqlite [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8631118Z [32;1m✓ [0m[34;1mbcmath [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8666476Z [32;1m✓ [0m[34;1msoap [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8702072Z [32;1m✓ [0m[34;1mintl [0m[90;1mEnabled[0m
2023-10-30T15:03:56.8885453Z PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20230831/gd.so (/usr/lib/php/20230831/gd.so: undefined symbol: gdImageCreateFromAvif), /usr/lib/php/20230831/gd.so.so (/usr/lib/php/20230831/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
2023-10-30T15:03:57.0762114Z PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20230831/gd.so (/usr/lib/php/20230831/gd.so: undefined symbol: gdImageCreateFromAvif), /usr/lib/php/20230831/gd.so.so (/usr/lib/php/20230831/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
2023-10-30T15:04:16.5070323Z [32;1m✓ [0m[34;1mgd [0m[90;1mInstalled and enabled[0m
2023-10-30T15:04:16.5224924Z [32;1m✓ [0m[34;1mexif [0m[90;1mEnabled[0m
2023-10-30T15:04:16.5258791Z [32;1m✓ [0m[34;1miconv [0m[90;1mEnabled[0m
2023-10-30T15:04:16.5295306Z [32;1m✓ [0m[34;1mimagick [0m[90;1mEnabled[0m
2023-10-30T15:04:16.5332825Z [32;1m✓ [0m[34;1mfileinfo [0m[90;1mEnabled[0m
2023-10-30T15:04:16.5333517Z 
2023-10-30T15:04:16.5333869Z [90;1m==> [0m[37;1mSetup Tools[0m
2023-10-30T15:04:16.9475785Z [32;1m✓ [0m[34;1mcomposer [0m[90;1mAdded composer 2.6.5[0m
2023-10-30T15:04:16.9476566Z 
2023-10-30T15:04:16.9476893Z [90;1m==> [0m[37;1mSetup Coverage[0m
2023-10-30T15:04:17.2450975Z [32;1m✓ [0m[34;1mnone [0m[90;1mDisabled Xdebug and PCOV[0m
2023-10-30T15:04:17.2451778Z 
2023-10-30T15:04:17.2452132Z [90;1m==> [0m[37;1m#StandWithUkraine[0m
2023-10-30T15:04:17.2453185Z [32;1m✓ [0m[34;1mread-more [0m[90;1mhttps://setup-php.com/support-ukraine[0m
```

**Comment by shivammathur** [comment]
@jasonvarga Please reproduce the bug in a public workflow and create a new issue with the details.
